// <auto-generated />
using System;
using BackEnd;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240806234941_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackEnd.Models.MsStorageLocation", b =>
                {
                    b.Property<string>("LocationId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("location_id");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location_name");

                    b.HasKey("LocationId")
                        .HasName("PK_ms_storage_location");

                    b.ToTable("ms_storage_location", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.MsUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId")
                        .HasName("PK_ms_user");

                    b.ToTable("ms_user", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.TrBpkb", b =>
                {
                    b.Property<string>("AgreementNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("agreement_number");

                    b.Property<DateTime>("BpkbDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("bpkb_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("BpkbDateIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("bpkb_date_in")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("BpkbNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bpkb_no");

                    b.Property<string>("BranchId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("branch_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FakturDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("faktur_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FakturNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("faktur_no");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("last_updated_by");

                    b.Property<DateTime>("LastUpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_updated_on")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LocationId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("location_id");

                    b.Property<string>("PoliceNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("police_no");

                    b.HasKey("AgreementNumber")
                        .HasName("PK_tr_bpkb");

                    b.HasIndex("LocationId");

                    b.ToTable("tr_bpkb", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.TrBpkb", b =>
                {
                    b.HasOne("BackEnd.Models.MsStorageLocation", "MsStorageLocation")
                        .WithMany("TrBpkbs")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK_tr_bpkb_ms_storage_location");

                    b.Navigation("MsStorageLocation");
                });

            modelBuilder.Entity("BackEnd.Models.MsStorageLocation", b =>
                {
                    b.Navigation("TrBpkbs");
                });
#pragma warning restore 612, 618
        }
    }
}
